### ISSUE TITLE
Eval

### ISSUE THREAD

**Issue by samirma** [EricZeiberg/MachineLearning#1]
Hello
I would like to know how can I eval the model. I did some attempts but none of them worked fo me.

For example:
```
flags.DEFINE_string('checkpoint',  "checkpoints/-2400", 'Checkpoint file')
flags.DEFINE_boolean('eval', True, 'Whether to train or evaluate')
flags.DEFINE_string('image', "images/0065UL-330.png", 'Image file for evaluation')
```
Return:
```
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "learn.py", line 86, in <module>
    predictions = model.predict(img)
  File "/Users/samirantonio/anaconda/envs/flappybird/lib/python2.7/site-packages/tflearn/models/dnn.py", line 204, in predict
    return self.predictor.predict(feed_dict)
  File "/Users/samirantonio/anaconda/envs/flappybird/lib/python2.7/site-packages/tflearn/helpers/evaluator.py", line 69, in predict
    o_pred = self.session.run(output, feed_dict=feed_dict).tolist()
  File "/Users/samirantonio/anaconda/envs/flappybird/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Users/samirantonio/anaconda/envs/flappybird/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 36, 36, 3) for Tensor u'InputData/X:0', which has shape '(?, 125, 30, 3)'
```

**Comment by EricZeiberg** [comment]
Hi, 

This error could be caused by passing the script an image in a format that it is not familiar with. In any case, I mainly wrote this code for my own purposes and didn't really write it to be installed on other machines. If you want, you can try setting it up on your end, but I'm afraid you are on your own. 

Thanks, 
Eric
